name: Send Dispatch Event
description: Sends dispatch event
inputs:
  github_token:
    description: The GitHub token.
    default: ${{ github.token }}
    required: false
  Organization:
    description: Organization.
    required: false
  Repository:
    description: Repository.
    required: false
    
  data:
    description: The dispatch event data.
    required: false

runs:
  using: 'composite'
  steps:
    - run: ls
