name: Send Dispatch Event
description: Sends dispatch event
inputs:
  github_token:
    description: The GitHub token.
    default: ${{ github.token }}
    required: true
  Organization:
    description: Organization.
    required: true
  Repository:
    description: Repository.
    required: true
    
  data:
    description: The dispatch event data.
    required: true

runs:
  using: 'composite'
  steps:
    - run: ls
