name: print-test

on: 
  workflow_dispatch:
  
jobs:
  install-chrome:
        runs-on: ubuntu-latest
        steps:
            - uses: browser-actions/setup-chrome@v1
            - run: chrome --version
            - run: chrome www.google.com
